### ISSUE TITLE
Could you help me be like you? 😁

### ISSUE THREAD

**Issue by fakefarm** [jfcherng/my-Sublime-Text-settings#2]
Hi @jfcherng,

I greatly admire how you manage SublimeText.You helped me out a few years ago with [navigation arrows](https://forum.sublimetext.com/t/how-to-switch-to-2nd-autocomplete-suggestion-list-without-arrows/54787) in the forum. (Thanks again!)  I recently updated to Sublime 4 and since then all my preferences have gone out of whack.  I don't have a good grasp on how to manage everything. My first impulse was to find your system and just clone it. However, not everything you use is compatible with my Ruby heavy workflow. Have you ever helped someone do what you've done with their sublime settings? Meaning, I'd love to:
- manage my settings on git
- know what each directory is used  for, and how to find such packages
- How to get a new sublime (or new mac) up and running with such a repo.
- (and anything else)

Any chance you have (or would be willing) to write up a step by step guide based on what you've done?

Regardless, I'm going to do my best to study what you have here.

Dave

**Comment by jfcherng** [comment]
> manage my settings on git
> know what each directory is used for, and how to find such packages

When a package installed by Package Control, it goes to
- `Installed Packages/` if the author doesn't create a `.no-sublime-package` file in the root of its package. This is usually the case.
- `Packages/` if the author creates a `.no-sublime-package` file in the root of its package, which is not recommended.

You don't have to include `Installed Packages/` because packages in it will be auto downloaded by Package Control (unless you are not using a version which comes from Package Control). Your custom plugin overwrite is in `Packages/` as well, so you have to distinguish what are made by yourself in `Packages/`. And ignore packages which are auto installed by Package Control without overwritten. Like https://github.com/jfcherng-sublime/ST-my-settings/blob/e62ab583088b846785790331c41d9d19575aac64/Packages/.gitignore

- The `Package Storage/` directory is only used by LSP currently and will be auto downloaded so it doesn't have to be included.
- `my_dependencies/` and `typings/` are my personal belongings which I want them to be shipped along with ST just for convenience.

# Privacy

Note that to prevent from leaking your ST/SM license, the `Local` directory should be in your `.gitignore` like https://github.com/jfcherng-sublime/ST-my-settings/blob/e62ab583088b846785790331c41d9d19575aac64/.gitignore#L4
Also, nowadays, GitHub free account can create private repositories as well if you don't want your settings to be public.

# Reference

There is a [Syncing](https://packagecontrol.io/docs/syncing) section on Package Control's official site.

**Comment by fakefarm** [comment]
@jfcherng,
This is great! I am going to apply what you've shared with me and would like to keep you posted with progress, if that's okay by you. 

Thanks again!  🙏

**Comment by jfcherng** [comment]
Close due to inactivity.
